#!/bin/bash

# Rotazione schermo.
# Valori ammessi: normal, left, right, inverted
screen_rotation="left"

# Array con gli URL e la durata del sonno per ciascun sito
# Usa questa sintassi per ogni riga: "URL SECONDI"
# Per rendere attive le modifiche riavviare il desktop manager in uso
# sudo systemctl restart lightdm.service
urls=(
    "https://www.debian.org/ 3"
    "https://it.wikipedia.org 5"
    # Aggiungi altri siti che vuoi mostrare
)

