#!/bin/sh

SCREEN_ROTATION=normal

# Legge il file di configurazione
if [ -f /etc/default/bsignage ]; then
	. /etc/default/bsignage
fi


# Applica la rotazione dello schermo usando come default 'normal'
# effettua anche un controllo sui valori ammessi
case "${SCREEN_ROTATION:-normal}" in
	normal|left|right|inverted)
		(
			for _ in 1 2 3 4 5 6 7 8 9 10; do
				xrandr -o "${SCREEN_ROTATION:-normal}" >> /tmp/bsignage-xrandr.log 2>&1 && break
				sleep 1
			done
		) &
		;;
	*)
		echo "Valore SCREEN_ROTATION non valido: ${SCREEN_ROTATION}" >> /tmp/bsignage-xrandr.log
		;;
esac

(sleep 2; xset -dpms s off) &
(sleep 5; /usr/sbin/bsignage) &
